* CamomeGcWatcher

  Watch Google calenar and send events via gRPC to upstreams.

** Installation

   Add this line to your application's Gemfile:

   #+BEGIN_SRC ruby
     gem 'camome_gc_watcher'
   #+END_SRC

   And then execute:

   #+BEGIN_SRC ruby
     $ bundle
   #+END_SRC

   Or install it yourself as:

   #+BEGIN_SRC ruby
     $ gem install camome_gc_watcher
   #+END_SRC

   From source code:
   #+BEGIN_SRC ruby
     $ bundle install --path=vendor/bundle --binstubs=bin
   #+END_SRC

** Usage

   TODO: Write usage instructions here

** Development

   After checking out the repo,
   #+BEGIN_SRC ruby
     $ bin/grpc_tools_ruby_protoc -I proto/ --ruby_out=lib/proto --grpc_out=lib/proto proto/camome/calendar/event.proto
   #+END_SRC

   and run =bin/setup= to install
   dependencies. Then, run =rake spec= to run the tests. You can also
   run =bin/console= for an interactive prompt that will allow you to
   experiment.

   To install this gem onto your local machine, run
   =bundle exec rake install=. To release a new version,
   update the version number in
   =version.rb=, and then run =bundle exec rake release=, which will
   create a git tag for the version, push git commits and tags, and push
   the =.gem= file to [[https://rubygems.org][rubygems.org]]

** Contributing

   Bug reports and pull requests are welcome on GitHub at
   https://github.com/yoshinari-nomura/camome_gc_watcher.

** License

   The gem is available as open source under the terms of the
   [[https://opensource.org/licenses/MIT][MIT License]].
